# Generated by Django 5.0 on 2024-02-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project_github_description_project_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_url_title',
            field=models.CharField(default='Github: Title of repo', max_length=60),
        ),
    ]
